// <auto-generated />
namespace CsharpSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_020));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281936269_0.20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
