// <auto-generated />
namespace CsharpSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _009 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_009));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171830066_0.09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
